// 辞書データプール
var VOCABULARY_POOL = [
  { w: 'agenda', m: '協議事項、議題', p: '/əˈdʒen.də/', e: 'What is on the agenda for today’s meeting?', j: '今日の会議の議題は何ですか？' },
  { w: 'allocate', m: '配分する、割り当てる', p: '/ˈæl.ə.keɪt/', e: 'More resources have been allocated to the backend team.', j: 'バックエンドチームに、より多くのリソースが割り当てられました。' },
  { w: 'collaborate', m: '共同で働く、協力する', p: '/kəˈlæb.ə.reɪt/', e: 'Let’s collaborate on this new project.', j: 'この新しいプロジェクトで協力しましょう。' },
  { w: 'comply', m: '従う、順守する', p: '/kəmˈplaɪ/', e: 'All products must comply with safety standards.', j: 'すべての製品は安全基準を順守しなければならない。' },
  { w: 'negotiate', m: '交渉する', p: '/nəˈɡoʊ.ʃi.eɪt/', e: 'She managed to negotiate a better contract.', j: '彼女はより良い契約を交渉で勝ち取った。' },
  { w: 'revenue', m: '収益、歳入', p: '/ˈrev.ə.nuː/', e: 'The company reported a 10% increase in revenue.', j: 'その会社は収益の10%増加を報告した。' },
  { w: 'implement', m: '実行する、実施する', p: '/ˈɪm.plə.ment/', e: 'We are currently implementing the new payment gateway.', j: '現在、新しい決済ゲートウェイを実装しています。' },
  { w: 'feasible', m: '実現可能な', p: '/ˈfiː.zə.bəl/', e: 'The plan is financially feasible.', j: 'その計画は財政的に実現可能だ。' },
  { w: 'discrepancy', m: '不一致、食い違い', p: '/dɪˈskrep.ən.si/', e: 'We found a discrepancy in the financial report.', j: '財務報告書に不一致が見つかりました。' },
  { w: 'incentive', m: '動機、励み、インセンティブ', p: '/ɪnˈsen.tɪv/', e: 'The company offers cash incentives for good performance.', j: '会社は優れた業績に対して現金のインセンティブを提供している。' },
  { w: 'natural', m: '自然に由来する、天然の', p: '/ˈnætʃ.ər.əl/', e: 'Many people prefer natural products with fewer chemicals.', j: '多くの人は化学物質の少ない天然製品を好む。' },
  { w: 'dedicated', m: '専用の、特定目的のための', p: '/ˈded.ɪ.keɪ.tɪd/', e: 'This facility has a dedicated line for customer support.', j: 'この施設には顧客サポート専用の回線がある。' },
  { w: 'co-opt', m: '（意図的に）取り込む、利用する', p: '/koʊˈɒpt/', e: 'They tried to co-opt local leaders into the planning process.', j: '彼らは計画プロセスに地元の指導者を取り込もうとした。' },
  { w: 'circuit', m: '回路、循環する経路', p: '/ˈsɝː.kɪt/', e: 'The engineer inspected the electrical circuit for any faults.', j: '技師は電気回路に故障がないか点検した。' },
  { w: 'inevitably', m: '必然的に、避けられずに', p: '/ɪˈnev.ɪ.bli/', e: 'Inevitably, delays increased the project cost.', j: '必然的に、遅延はプロジェクトの費用を増加させた。' },
  { w: 'intricate', m: '複雑な、入り組んだ', p: '/ˈɪn.trɪ.kət/', e: 'The watch contains an intricate arrangement of gears.', j: 'その時計は入り組んだ歯車の配置を持っている。' },
  { w: 'deploy', m: '（システムを）デプロイする、配置する', p: '/dɪˈplɔɪ/', e: 'The updates were successfully deployed to the staging environment.', j: 'アップデートはステージング環境へ正常にデプロイされました。' },
  { w: 'finalize', m: '〜を最終決定する、仕上げる', p: '/ˈfaɪ.nə.laɪz/', e: 'I will finalize the database schema by noon.', j: '正午までにデータベースのスキーマを確定させます。' },
  { w: 'proceed', m: '進行する、進める', p: '/prəˈsiːd/', e: 'We can proceed with the next phase of development.', j: '開発の次のフェーズに進むことができます。' },
  { w: 'on track', m: '順調で、予定通りで', p: '', e: 'Feature development is on track for the Friday release.', j: '機能開発は金曜日のリリースに向けて順調です。' },
  { w: 'delay', m: '遅れ、〜を遅らせる', p: '/dɪˈleɪ/', e: 'There is a slight delay in the code review process.', j: 'コードレビューのプロセスにわずかな遅れが出ています。' },
  { w: 'postpone', m: '〜を延期する', p: '/pəˈspoʊn/', e: 'We decided to postpone the user test until next Tuesday.', j: 'ユーザーテストを次の火曜日まで延期することにしました。' },
  { w: 'accelerate', m: '〜を加速させる、早める', p: '/əkˈsel.ə.reɪt/', e: 'We need to accelerate the testing phase to meet the deadline.', j: '締め切りに間に合わせるため、テストフェーズを加速させる必要があります。' },
  { w: 'fall behind', m: '遅れる、予定より遅れてしまう', p: '', e: 'We have fallen behind schedule due to a major bug.', j: '重大なバグのせいでスケジュールより遅れてしまっています。' },
  { w: 'catch up', m: '追いつく', p: '', e: 'I will work on this over the weekend to catch up.', j: '追いつくために、週末にこれに対応します。' },
  { w: 'issue', m: '課題、問題（バグやトラブルなど）', p: '/ˈɪʃ.uː/', e: 'We encountered a critical issue regarding data synchronization.', j: 'データ同期に関する致命的な問題が発生しました。' },
  { w: 'resolve', m: '〜を解決する', p: '/rɪˈzɒlv/', e: 'The login error has been completely resolved.', j: 'ログインエラーは完全に解決されました。' },
  { w: 'complication', m: '複雑化、面倒な事態', p: '/ˌkɒm.plɪˈkeɪ.ʃən/', e: 'We faced some complications with the third-party API.', j: 'サードパーティ製APIでいくつかの面倒な問題に直面しました。' },
  { w: 'blocker', m: '進行を妨げている要因、障害', p: '/ˈblɒk.ər/', e: 'Currently, I have no blockers. I can keep going.', j: '現在、進捗を妨げる障害はありません。このまま進められます。' },
  { w: 'investigate', m: '〜を調査する、調べる', p: '/ɪnˈves.tɪ.ɡeɪt/', e: 'We are investigating the cause of the system slow-down.', j: 'システム速度低下の原因を調査しているところです。' },
  { w: 'scope', m: '開発範囲、対象範囲', p: '/skoʊp/', e: 'This feature is out of scope for the current sprint.', j: 'この機能は、現在のスプリントの範囲外です。' },
  { w: 'pending', m: '保留中の、未決の', p: '/ˈpen.dɪŋ/', e: 'This task is pending client approval.', j: 'このタスクはクライアントの承認待ちで保留中です。' },
  { w: 'anticipate', m: '〜を予想する、見込む', p: '/ænˈtɪs.ɪ.peɪt/', e: 'We anticipate completing the task by tomorrow evening.', j: '明日の夕方までにタスクが完了すると見込んでいます。' },
  { w: 'requirement', m: '要件、必要な条件', p: '/rɪˈkwaɪər.mənt/', e: 'We are reviewing the security requirements again.', j: 'セキュリティ要件をもう一度レビューしています。' }
];

var SHADOWING_SENTENCES = [
  { text: 'The meeting starts at nine o’clock.', phonetic: '/ðə ˈmiː.tɪŋ stɑːrts æt naɪn əˈklɑːk./', translation: '会議は9時に始まります。' },
  { text: 'Please send the revised schedule by this afternoon.', phonetic: '/pliːz sɛnd ðə rɪˈvaɪzd ˈskedʒ.uːl baɪ ðɪs ˌɑːf.təˈnuːn./', translation: '修正したスケジュールを今日の午後までに送ってください。' },
  { text: 'I will follow up with the client tomorrow.', phonetic: '/aɪ wɪl ˈfɒl.oʊ ʌp wɪð ðə ˈklaɪ.ənt təˈmɒr.oʊ./', translation: '明日クライアントにフォローします。' },
  { text: 'Our team needs to finalize the budget today.', phonetic: '/aʊər tiːm niːdz tə ˈfaɪ.nə.laɪz ðə ˈbʌdʒ.ɪt təˈdeɪ./', translation: '私たちのチームは今日予算を最終決定する必要があります。' },
  { text: 'Could you explain the key deliverables once more?', phonetic: '/kʊd juː ɪkˈspleɪn ðə kiː dɪˈlɪv.ər.ə.bəlz wʌns mɔːr?/', translation: '主要な成果物をもう一度説明していただけますか？' },
  { text: 'We are waiting for final approval from the board.', phonetic: '/wiː ɑːr ˈweɪ.tɪŋ fɔːr ˈfaɪ.nəl əˈpruː.vəl frəm ðə bɔːrd./', translation: '取締役会からの最終承認を待っています。' },
  { text: 'The product launch has been postponed until next month.', phonetic: '/ðə ˈprɒd.ʌkt lɔːntʃ hæz bɪn pəˈspoʊnd ʌnˈtɪl nɛkst mʌnθ./', translation: '製品の発売は来月まで延期されました。' },
  { text: 'Let’s review the quarterly targets in the next meeting.', phonetic: '/lɛts rɪˈvjuː ðə ˈkwɔːr.tɚ.li ˈtɑːr.ɡəts ɪn ðə nɛkst ˈmiː.tɪŋ./', translation: '次の会議で四半期目標を確認しましょう。' },
  { text: 'Our current strategy needs a little more refinement.', phonetic: '/aʊər ˈkʌr.ənt ˈstræt.ə.dʒi niːdz ə ˈlɪt.əl mɔːr rɪˈfaɪn.mənt./', translation: '現在の戦略はもう少し改善が必要です。' },
  { text: 'I appreciate your prompt response on this issue.', phonetic: '/aɪ əˈpriː.ʃi.eɪt jɔːr prɒmpt rɪˈspɒns ɒn ðɪs ˈɪʃ.uː./', translation: 'この件について迅速なご対応に感謝します。' }
];
